name: Unit test

on: [push, pull_request]
jobs:
  one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Init node env
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm ci
      - name: Build product
        run: npm run build
        env:
          CI: true
